version: "3.9"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: irishmay/proj9:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
    logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
    links: 
      - redis 
  
  redis: 
    image: "redis:alpine"
    volumes:
      - #/host/path:/container/path
    networks:
      - default 
    ports: 
      - "4000:80"
    logging:
        driver: "json-file"
        options:
          max-size: "200k"
          max-file: "10"
  
