version: "3.9"

services:
  web:
    build: .
    ports:
      - "4000:4000"
    networks:
      - mynet
    # logging:
    #     driver: "json-file"
    #     options:
    #       max-size: "200k"
    #       max-file: "10"
    depends_on:
      - redis-server
  
  redis-server: 
    image: "redis:latest"
    #command: redis-server
    networks:
      - mynet

networks:
  mynet:

  # logging:
  #       driver: "json-file"
  #       options:
  #         max-size: "200k"
  #         max-file: "10"
  
