version: "3.9"

services:
  web:
    build: .
    # deploy:
    #   replicas: 5
    #   resources:
    #     limits:
    #       cpus: "0.1"
    #       memory: 50M
    #   restart_policy:
    #     condition: on-failure
    ports:
      - "4000:4000"
    networks:
      - mynet
    # logging:
    #     driver: "json-file"
    #     options:
    #       max-size: "200k"
    #       max-file: "10"
    links: 
      - redis 
  
  redis-server: 
    image: "redis:latest"
    volumes:
      - "./data:/data"
    networks:
      - mynet

networks:
  mynet:

  # logging:
  #       driver: "json-file"
  #       options:
  #         max-size: "200k"
  #         max-file: "10"
  
